package wordpress;
@:native('\\ParagonIE_Sodium_Crypto32')
extern class ParagonIE_Sodium_Crypto32 {
    @:phpClassConst static public final aead_chacha20poly1305_KEYBYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_NSECBYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_NPUBBYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_ABYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_IETF_KEYBYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_IETF_NSECBYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_IETF_NPUBBYTES:Dynamic;
    @:phpClassConst static public final aead_chacha20poly1305_IETF_ABYTES:Dynamic;
    @:phpClassConst static public final aead_xchacha20poly1305_IETF_KEYBYTES:Dynamic;
    @:phpClassConst static public final aead_xchacha20poly1305_IETF_NSECBYTES:Dynamic;
    @:phpClassConst static public final aead_xchacha20poly1305_IETF_NPUBBYTES:Dynamic;
    @:phpClassConst static public final aead_xchacha20poly1305_IETF_ABYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_SEEDBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_PUBLICKEYBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_SECRETKEYBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_BEFORENMBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_NONCEBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_MACBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_BOXZEROBYTES:Dynamic;
    @:phpClassConst static public final box_curve25519xsalsa20poly1305_ZEROBYTES:Dynamic;
    @:phpClassConst static public final onetimeauth_poly1305_BYTES:Dynamic;
    @:phpClassConst static public final onetimeauth_poly1305_KEYBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xsalsa20poly1305_KEYBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xsalsa20poly1305_NONCEBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xsalsa20poly1305_MACBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xsalsa20poly1305_BOXZEROBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xsalsa20poly1305_ZEROBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xchacha20poly1305_KEYBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xchacha20poly1305_NONCEBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xchacha20poly1305_MACBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xchacha20poly1305_BOXZEROBYTES:Dynamic;
    @:phpClassConst static public final secretbox_xchacha20poly1305_ZEROBYTES:Dynamic;
    @:phpClassConst static public final stream_salsa20_KEYBYTES:Dynamic;
    public static function aead_chacha20poly1305_decrypt(?message:String, ?ad:String, ?nonce:String, ?key:String):String;
    public static function aead_chacha20poly1305_encrypt(?message:String, ?ad:String, ?nonce:String, ?key:String):String;
    public static function aead_chacha20poly1305_ietf_decrypt(?message:String, ?ad:String, ?nonce:String, ?key:String):String;
    public static function aead_chacha20poly1305_ietf_encrypt(?message:String, ?ad:String, ?nonce:String, ?key:String):String;
    public static function aead_xchacha20poly1305_ietf_decrypt(?message:String, ?ad:String, ?nonce:String, ?key:String):String;
    public static function aead_xchacha20poly1305_ietf_encrypt(?message:String, ?ad:String, ?nonce:String, ?key:String):String;
    public static function auth(message:String, key:String):String;
    public static function auth_verify(mac:String, message:String, key:String):Bool;
    public static function box(plaintext:String, nonce:String, keypair:String):String;
    public static function box_seal(message:String, publicKey:String):String;
    public static function box_seal_open(message:String, keypair:String):String;
    public static function box_beforenm(sk:String, pk:String):String;
    public static function box_keypair():String;
    public static function box_seed_keypair(seed:String):String;
    public static function box_keypair_from_secretkey_and_publickey(sKey:String, pKey:String):String;
    public static function box_secretkey(keypair:String):String;
    public static function box_publickey(keypair:String):String;
    public static function box_publickey_from_secretkey(sKey:String):String;
    public static function box_open(ciphertext:String, nonce:String, keypair:String):String;
    public static function generichash(message:String, ?key:Dynamic, ?outlen:Int):String;
    public static function generichash_final(ctx:String, ?outlen:Int):String;
    public static function generichash_init(?key:String, ?outputLength:Int):String;
    public static function generichash_init_salt_personal(?key:String, ?outputLength:Int, ?salt:String, ?personal:String):String;
    public static function generichash_update(ctx:String, message:String):String;
    public static function keyExchange(my_sk:String, their_pk:String, client_pk:String, server_pk:String):String;
    public static function scalarmult(sKey:String, pKey:String):String;
    public static function scalarmult_base(secret:String):String;
    protected static function scalarmult_throw_if_zero(q:String):Void;
    public static function secretbox(plaintext:String, nonce:String, key:String):String;
    public static function secretbox_open(ciphertext:String, nonce:String, key:String):String;
    public static function secretbox_xchacha20poly1305(plaintext:String, nonce:String, key:String):String;
    public static function secretbox_xchacha20poly1305_open(ciphertext:String, nonce:String, key:String):String;
    public static function secretstream_xchacha20poly1305_init_push(key:String):Array<wordpress. string>;
    public static function secretstream_xchacha20poly1305_init_pull(key:String, header:String):String;
    public static function secretstream_xchacha20poly1305_push(state:String, msg:String, ?aad:String, ?tag:Int):String;
    public static function secretstream_xchacha20poly1305_pull(state:String, cipher:String, ?aad:String):Dynamic;
    public static function secretstream_xchacha20poly1305_rekey(state:String):Void;
    public static function sign_detached(message:String, sk:String):String;
    public static function sign(message:String, sk:String):String;
    public static function sign_open(signedMessage:String, pk:String):String;
    public static function sign_verify_detached(signature:String, message:String, pk:String):Bool;
}

