package wordpress;
@:native('\\SimplePie')
extern class SimplePie {
    public var data:Array<Dynamic>;
    public var error:Dynamic;
    public var sanitize:Dynamic;
    public var useragent:String;
    public var feed_url:Dynamic;
    public var file:Dynamic;
    public var raw_data:Dynamic;
    public var timeout:Int;
    public var force_fsockopen:Bool;
    public var force_feed:Bool;
    public var cache:Bool;
    public var cache_duration:Int;
    public var autodiscovery_cache_duration:Int;
    public var cache_location:String;
    public var cache_name_function:String;
    public var order_by_date:Bool;
    public var input_encoding:Dynamic;
    public var autodiscovery:Int;
    public var registry:Dynamic;
    public var max_checked_feeds:Int;
    public var all_discovered_feeds:Array<Dynamic>;
    public var image_handler:String;
    public var multifeed_url:Array<Dynamic>;
    public var multifeed_objects:Array<Dynamic>;
    public var config_settings:Array<Dynamic>;
    public var item_limit:Int;
    public var strip_attributes:Array<Dynamic>;
    public var strip_htmltags:Array<Dynamic>;
    public function __construct():Dynamic;
    public function __toString():Dynamic;
    public function __destruct():Dynamic;
    public function force_feed(?enable:Bool):Dynamic;
    public function set_feed_url(url:Dynamic):Dynamic;
    public function set_file(file:Dynamic):Bool;
    public function set_raw_data(data:String):Dynamic;
    public function set_timeout(?timeout:Int):Dynamic;
    public function force_fsockopen(?enable:Bool):Dynamic;
    public function enable_cache(?enable:Bool):Dynamic;
    public function set_cache_duration(?seconds:Int):Dynamic;
    public function set_autodiscovery_cache_duration(?seconds:Int):Dynamic;
    public function set_cache_location(?location:String):Dynamic;
    public function enable_order_by_date(?enable:Bool):Dynamic;
    public function set_input_encoding(?encoding:String):Dynamic;
    public function set_autodiscovery_level(?level:Int):Dynamic;
    public function get_registry():wordpress.SimplePie_Registry;
    public function set_cache_class(?class_:Dynamic):Dynamic;
    public function set_locator_class(?class_:Dynamic):Dynamic;
    public function set_parser_class(?class_:Dynamic):Dynamic;
    public function set_file_class(?class_:Dynamic):Dynamic;
    public function set_sanitize_class(?class_:Dynamic):Dynamic;
    public function set_item_class(?class_:Dynamic):Dynamic;
    public function set_author_class(?class_:Dynamic):Dynamic;
    public function set_category_class(?class_:Dynamic):Dynamic;
    public function set_enclosure_class(?class_:Dynamic):Dynamic;
    public function set_caption_class(?class_:Dynamic):Dynamic;
    public function set_copyright_class(?class_:Dynamic):Dynamic;
    public function set_credit_class(?class_:Dynamic):Dynamic;
    public function set_rating_class(?class_:Dynamic):Dynamic;
    public function set_restriction_class(?class_:Dynamic):Dynamic;
    public function set_content_type_sniffer_class(?class_:Dynamic):Dynamic;
    public function set_source_class(?class_:Dynamic):Dynamic;
    public function set_useragent(?ua:String):Dynamic;
    public function set_cache_name_function(?function_:Dynamic):Dynamic;
    public function set_stupidly_fast(?set:Bool):Dynamic;
    public function set_max_checked_feeds(?max:Int):Dynamic;
    public function remove_div(?enable:Dynamic):Dynamic;
    public function strip_htmltags(?tags:Dynamic, ?encode:Dynamic):Dynamic;
    public function encode_instead_of_strip(?enable:Dynamic):Dynamic;
    public function strip_attributes(?attribs:Dynamic):Dynamic;
    public function set_output_encoding(?encoding:String):Dynamic;
    public function strip_comments(?strip:Dynamic):Dynamic;
    public function set_url_replacements(?element_attribute:Dynamic):Dynamic;
    public function set_image_handler(?page:wordpress.Str, ?qs:wordpress.Str):Dynamic;
    public function set_item_limit(?limit:Int):Dynamic;
    public function init():Bool;
    protected function fetch_data(cache:Dynamic):Dynamic;
    public function error():Dynamic;
    public function get_raw_data():Dynamic;
    public function get_encoding():String;
    public function handle_content_type(?mime:String):Dynamic;
    public function get_type():Int;
    public function subscribe_url():Dynamic;
    public function get_feed_tags(namespace:String, tag:String):Array<Dynamic>;
    public function get_channel_tags(namespace:String, tag:String):Array<Dynamic>;
    public function get_image_tags(namespace:String, tag:String):Array<Dynamic>;
    public function get_base(?element:Array<Dynamic>):String;
    public function sanitize(data:String, type:Int, ?base:String):String;
    public function get_title():Dynamic;
    public function get_category(?key:Int):Dynamic;
    public function get_categories():Dynamic;
    public function get_author(?key:Int):Dynamic;
    public function get_authors():Dynamic;
    public function get_contributor(?key:Int):Dynamic;
    public function get_contributors():Dynamic;
    public function get_link(?key:Int, ?rel:String):Dynamic;
    public function get_permalink():Dynamic;
    public function get_links(?rel:String):Dynamic;
    public function get_all_discovered_feeds():Dynamic;
    public function get_description():Dynamic;
    public function get_copyright():Dynamic;
    public function get_language():Dynamic;
    public function get_latitude():Dynamic;
    public function get_longitude():Dynamic;
    public function get_image_title():Dynamic;
    public function get_image_url():Dynamic;
    public function get_image_link():Dynamic;
    public function get_image_width():Dynamic;
    public function get_image_height():Dynamic;
    public function get_item_quantity(?max:Int):Int;
    public function get_item(?key:Int):Dynamic;
    public function get_items(?start:Int, ?end:Int):Dynamic;
    public function set_favicon_handler(?page:Dynamic, ?qs:Dynamic):Dynamic;
    public function get_favicon():Dynamic;
    public function __call(method:String, args:Array<Dynamic>):Dynamic;
    public static function sort_items(a:wordpress.SimplePie, b:wordpress.SimplePie):Bool;
    public static function merge_items(urls:Array<Dynamic>, ?start:Int, ?end:Int, ?limit:Int):Array<Dynamic>;
}

