package wordpress;
@:native('\\SimplePie_Enclosure')
extern class SimplePie_Enclosure {
    public var bitrate:Dynamic;
    public var captions:Dynamic;
    public var categories:Dynamic;
    public var channels:Dynamic;
    public var copyright:Dynamic;
    public var credits:Dynamic;
    public var description:Dynamic;
    public var duration:Dynamic;
    public var expression:Dynamic;
    public var framerate:Dynamic;
    public var handler:Dynamic;
    public var hashes:Dynamic;
    public var height:Dynamic;
    public var javascript:Dynamic;
    public var keywords:Dynamic;
    public var lang:Dynamic;
    public var length:Dynamic;
    public var link:Dynamic;
    public var medium:Dynamic;
    public var player:Dynamic;
    public var ratings:Dynamic;
    public var restrictions:Dynamic;
    public var samplingrate:Dynamic;
    public var thumbnails:Dynamic;
    public var title:Dynamic;
    public var type:Dynamic;
    public var width:Dynamic;
    public function __construct(?link:Dynamic, ?type:Dynamic, ?length:Dynamic, ?javascript:Dynamic, ?bitrate:Dynamic, ?captions:Dynamic, ?categories:Dynamic, ?channels:Dynamic, ?copyright:Dynamic, ?credits:Dynamic, ?description:Dynamic, ?duration:Dynamic, ?expression:Dynamic, ?framerate:Dynamic, ?hashes:Dynamic, ?height:Dynamic, ?keywords:Dynamic, ?lang:Dynamic, ?medium:Dynamic, ?player:Dynamic, ?ratings:Dynamic, ?restrictions:Dynamic, ?samplingrate:Dynamic, ?thumbnails:Dynamic, ?title:Dynamic, ?width:Dynamic):Dynamic;
    public function __toString():String;
    public function get_bitrate():Dynamic;
    public function get_caption(?key:Int):Dynamic;
    public function get_captions():Dynamic;
    public function get_category(?key:Int):Dynamic;
    public function get_categories():Dynamic;
    public function get_channels():Dynamic;
    public function get_copyright():Dynamic;
    public function get_credit(?key:Int):Dynamic;
    public function get_credits():Dynamic;
    public function get_description():Dynamic;
    public function get_duration(?convert:String):Dynamic;
    public function get_expression():String;
    public function get_extension():Dynamic;
    public function get_framerate():Dynamic;
    public function get_handler():Dynamic;
    public function get_hash(?key:Int):Dynamic;
    public function get_hashes():Dynamic;
    public function get_height():Dynamic;
    public function get_language():Dynamic;
    public function get_keyword(?key:Int):Dynamic;
    public function get_keywords():Dynamic;
    public function get_length():Float;
    public function get_link():Dynamic;
    public function get_medium():Dynamic;
    public function get_player():Dynamic;
    public function get_rating(?key:Int):Dynamic;
    public function get_ratings():Dynamic;
    public function get_restriction(?key:Int):Dynamic;
    public function get_restrictions():Dynamic;
    public function get_sampling_rate():Dynamic;
    public function get_size():Dynamic;
    public function get_thumbnail(?key:Int):Dynamic;
    public function get_thumbnails():Dynamic;
    public function get_title():Dynamic;
    public function get_type():Dynamic;
    public function get_width():Dynamic;
    public function native_embed(?options:Dynamic):String;
    public function embed(?options:Dynamic, ?native:Bool):String;
    public function get_real_type(?find_handler:Bool):String;
}

