package wordpress;
@:native('\\WP_Http')
extern class WP_Http {
    @:phpClassConst static public final HTTP_CONTINUE:Dynamic;
    @:phpClassConst static public final SWITCHING_PROTOCOLS:Dynamic;
    @:phpClassConst static public final PROCESSING:Dynamic;
    @:phpClassConst static public final EARLY_HINTS:Dynamic;
    @:phpClassConst static public final OK:Dynamic;
    @:phpClassConst static public final CREATED:Dynamic;
    @:phpClassConst static public final ACCEPTED:Dynamic;
    @:phpClassConst static public final NON_AUTHORITATIVE_INFORMATION:Dynamic;
    @:phpClassConst static public final NO_CONTENT:Dynamic;
    @:phpClassConst static public final RESET_CONTENT:Dynamic;
    @:phpClassConst static public final PARTIAL_CONTENT:Dynamic;
    @:phpClassConst static public final MULTI_STATUS:Dynamic;
    @:phpClassConst static public final IM_USED:Dynamic;
    @:phpClassConst static public final MULTIPLE_CHOICES:Dynamic;
    @:phpClassConst static public final MOVED_PERMANENTLY:Dynamic;
    @:phpClassConst static public final FOUND:Dynamic;
    @:phpClassConst static public final SEE_OTHER:Dynamic;
    @:phpClassConst static public final NOT_MODIFIED:Dynamic;
    @:phpClassConst static public final USE_PROXY:Dynamic;
    @:phpClassConst static public final RESERVED:Dynamic;
    @:phpClassConst static public final TEMPORARY_REDIRECT:Dynamic;
    @:phpClassConst static public final PERMANENT_REDIRECT:Dynamic;
    @:phpClassConst static public final BAD_REQUEST:Dynamic;
    @:phpClassConst static public final UNAUTHORIZED:Dynamic;
    @:phpClassConst static public final PAYMENT_REQUIRED:Dynamic;
    @:phpClassConst static public final FORBIDDEN:Dynamic;
    @:phpClassConst static public final NOT_FOUND:Dynamic;
    @:phpClassConst static public final METHOD_NOT_ALLOWED:Dynamic;
    @:phpClassConst static public final NOT_ACCEPTABLE:Dynamic;
    @:phpClassConst static public final PROXY_AUTHENTICATION_REQUIRED:Dynamic;
    @:phpClassConst static public final REQUEST_TIMEOUT:Dynamic;
    @:phpClassConst static public final CONFLICT:Dynamic;
    @:phpClassConst static public final GONE:Dynamic;
    @:phpClassConst static public final LENGTH_REQUIRED:Dynamic;
    @:phpClassConst static public final PRECONDITION_FAILED:Dynamic;
    @:phpClassConst static public final REQUEST_ENTITY_TOO_LARGE:Dynamic;
    @:phpClassConst static public final REQUEST_URI_TOO_LONG:Dynamic;
    @:phpClassConst static public final UNSUPPORTED_MEDIA_TYPE:Dynamic;
    @:phpClassConst static public final REQUESTED_RANGE_NOT_SATISFIABLE:Dynamic;
    @:phpClassConst static public final EXPECTATION_FAILED:Dynamic;
    @:phpClassConst static public final IM_A_TEAPOT:Dynamic;
    @:phpClassConst static public final MISDIRECTED_REQUEST:Dynamic;
    @:phpClassConst static public final UNPROCESSABLE_ENTITY:Dynamic;
    @:phpClassConst static public final LOCKED:Dynamic;
    @:phpClassConst static public final FAILED_DEPENDENCY:Dynamic;
    @:phpClassConst static public final UPGRADE_REQUIRED:Dynamic;
    @:phpClassConst static public final PRECONDITION_REQUIRED:Dynamic;
    @:phpClassConst static public final TOO_MANY_REQUESTS:Dynamic;
    @:phpClassConst static public final REQUEST_HEADER_FIELDS_TOO_LARGE:Dynamic;
    @:phpClassConst static public final UNAVAILABLE_FOR_LEGAL_REASONS:Dynamic;
    @:phpClassConst static public final INTERNAL_SERVER_ERROR:Dynamic;
    @:phpClassConst static public final NOT_IMPLEMENTED:Dynamic;
    @:phpClassConst static public final BAD_GATEWAY:Dynamic;
    @:phpClassConst static public final SERVICE_UNAVAILABLE:Dynamic;
    @:phpClassConst static public final GATEWAY_TIMEOUT:Dynamic;
    @:phpClassConst static public final HTTP_VERSION_NOT_SUPPORTED:Dynamic;
    @:phpClassConst static public final VARIANT_ALSO_NEGOTIATES:Dynamic;
    @:phpClassConst static public final INSUFFICIENT_STORAGE:Dynamic;
    @:phpClassConst static public final NOT_EXTENDED:Dynamic;
    @:phpClassConst static public final NETWORK_AUTHENTICATION_REQUIRED:Dynamic;
    public function request(url:String, ?args:Dynamic):Dynamic;
    public static function normalize_cookies(cookies:Array<Dynamic>):wordpress.Requests_Cookie_Jar;
    public static function browser_redirect_compatibility(location:String, headers:Array<Dynamic>, data:Dynamic, options:Array<Dynamic>, original:wordpress.Requests_Response):Dynamic;
    public static function validate_redirects(location:String):Dynamic;
    public function _get_first_available_transport(args:Array<Dynamic>, ?url:String):Dynamic;
    public function post(url:String, ?args:Dynamic):Dynamic;
    public function get(url:String, ?args:Dynamic):Dynamic;
    public function head(url:String, ?args:Dynamic):Dynamic;
    public static function processResponse(strResponse:String):Array<Dynamic>;
    public static function processHeaders(headers:Dynamic, ?url:String):Array<Dynamic>;
    public static function buildCookieHeader(r:Array<Dynamic>):Dynamic;
    public static function chunkTransferDecode(body:String):String;
    public function block_request(uri:String):Bool;
    protected static function parse_url(url:String):Dynamic;
    public static function make_absolute_url(maybe_relative_path:String, url:String):String;
    public static function handle_redirects(url:String, args:Array<Dynamic>, response:Array<Dynamic>):Dynamic;
    public static function is_ip_address(maybe_ip:String):Dynamic;
}

