package wordpress;
@:native('\\WP_Rewrite')
extern class WP_Rewrite {
    public var permalink_structure:Dynamic;
    public var use_trailing_slashes:Dynamic;
    public var author_base:String;
    public var author_structure:Dynamic;
    public var date_structure:Dynamic;
    public var page_structure:Dynamic;
    public var search_base:String;
    public var search_structure:Dynamic;
    public var comments_base:String;
    public var pagination_base:String;
    public var comments_pagination_base:String;
    public var feed_base:String;
    public var comment_feed_structure:Dynamic;
    public var feed_structure:Dynamic;
    public var front:Dynamic;
    public var root:String;
    public var index:String;
    public var matches:String;
    public var rules:Dynamic;
    public var extra_rules:Array<Dynamic>;
    public var extra_rules_top:Array<Dynamic>;
    public var non_wp_rules:Array<Dynamic>;
    public var extra_permastructs:Array<Dynamic>;
    public var endpoints:Dynamic;
    public var use_verbose_rules:Bool;
    public var use_verbose_page_rules:Bool;
    public var rewritecode:Array<Dynamic>;
    public var rewritereplace:Array<Dynamic>;
    public var queryreplace:Array<Dynamic>;
    public var feeds:Array<Dynamic>;
    public function using_permalinks():Bool;
    public function using_index_permalinks():Bool;
    public function using_mod_rewrite_permalinks():Bool;
    public function preg_index(number:Int):String;
    public function page_uri_index():Array<Dynamic>;
    public function page_rewrite_rules():Array<String>;
    public function get_date_permastruct():Dynamic;
    public function get_year_permastruct():Dynamic;
    public function get_month_permastruct():Dynamic;
    public function get_day_permastruct():Dynamic;
    public function get_category_permastruct():Dynamic;
    public function get_tag_permastruct():Dynamic;
    public function get_extra_permastruct(name:String):Dynamic;
    public function get_author_permastruct():Dynamic;
    public function get_search_permastruct():Dynamic;
    public function get_page_permastruct():Dynamic;
    public function get_feed_permastruct():Dynamic;
    public function get_comment_feed_permastruct():Dynamic;
    public function add_rewrite_tag(tag:String, regex:String, query:String):Dynamic;
    public function remove_rewrite_tag(tag:String):Dynamic;
    public function generate_rewrite_rules(permalink_structure:String, ?ep_mask:Int, ?paged:Bool, ?feed:Bool, ?forcomments:Bool, ?walk_dirs:Bool, ?endpoints:Bool):Array<String>;
    public function generate_rewrite_rule(permalink_structure:String, ?walk_dirs:Bool):Array<Dynamic>;
    public function rewrite_rules():Array<String>;
    public function wp_rewrite_rules():Array<String>;
    public function mod_rewrite_rules():String;
    public function iis7_url_rewrite_rules(?add_parent_tags:Bool):String;
    public function add_rule(regex:String, query:Dynamic, ?after:String):Dynamic;
    public function add_external_rule(regex:String, query:String):Dynamic;
    public function add_endpoint(name:String, places:Int, ?query_var:Dynamic):Dynamic;
    public function add_permastruct(name:String, struct:String, ?args:Array<Dynamic>):Dynamic;
    public function remove_permastruct(name:String):Dynamic;
    public function flush_rules(?hard:Bool):Dynamic;
    public function init():Dynamic;
    public function set_permalink_structure(permalink_structure:String):Dynamic;
    public function set_category_base(category_base:String):Dynamic;
    public function set_tag_base(tag_base:String):Dynamic;
    public function __construct():Dynamic;
}

